config/routes.rb
Rails.application.routes.draw do


  get '/stuindex', to: 'studentprofiles#index'

 
  get 'reviews/index'

  get 'reviews/new'

  get 'reviews/edit'

  get 'reviews/show'

  get '/studentprofile', to: 'studentprofiles#new'
  post '/studentprofile', to: 'studentprofiles#create'
  get '/studentprofilepage/:id', to: 'studentprofiles#show', as: 'studentprofilepage'
  get '/studentprofilepage/:id/edit', to: 'studentprofiles#edit', as: 'edit'
  delete '/studentprofilepage/:id', to: 'studentprofiles#destroy', as: 'delete', method: :delete

  get '/famindex', to: 'familyprofiles#index'
  get '/familyprofile', to: 'familyprofiles#new'
  post '/familyprofile', to: 'familyprofiles#create'
  get '/familyprofilepage/:id', to: 'familyprofiles#show', as: 'familyprofilepage'
  get '/familyprofilepage/:id/edit', to: 'familyprofiles#edit', as: 'editfamily'
  delete '/familyprofilepage/:id', to: 'familyprofiles#destroy', as: 'deletefamily', method: :delete

  # get '/home', to: 'home#index'
  get '/about', to: 'home#about'

  devise_for :students

  devise_for :families, :controllers => { :omniauth_callbacks => "familyprofile/omniauth_callbacks" }
  devise_scope :family do
  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_families_session
end

  root 'home#index'
  
  

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/studentprofile.rb
class Studentprofile < ActiveRecord::Base

	belongs_to :student
	has_many :reviews

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  	def self.search(search)
        where("university LIKE ?", "%#{search}%")
        
    end 
	
end

app/controllers/studentprofiles_controller.rb
class StudentprofilesController < ApplicationController
	

	def index
		@studentprofiles = Studentprofile.all.order('created_at DESC')
		if params[:search]
			@studentprofiles = Studentprofile.search(params[:search]).order('created_at DESC')
		else 
			@studentprofiles = Studentprofile.all.order('created_at DESC')
		end 
	end  
	
	def new
		@studentprofile = Studentprofile.new
	end 

	
	def create
		@student = current_student
		@studentprofile = Studentprofile.new(studentprofile_params)
		if @studentprofile.save
			redirect_to studentprofilepage_path(@studentprofile), notice: "New profile created"
		else
			flash[:alert] = "There was a problem."
			render :new
		end 
	end 

	def show
		if current_student
			@studentprofile = current_student.studentprofile
		else 
			redirect_to root_path, notice: 'Please log in to view this page.'	
		end 
		@studentprofile = set_studentprofile
	end 

	def update
		set_studentprofile
		redirect_to studentprofile_path
	end 

	def edit
		set_studentprofile
		redirect_to studentprofile_path, alert: 'Profile edited'
	end 

	def destroy
		set_studentprofile
		@studentprofile.destroy
		redirect_to root_path, alert: 'Profile deleted.'
	end 

	private

	def set_studentprofile
		@studentprofile = Studentprofile.find(params[:id])
	end

	def studentprofile_params 
		params.require(:studentprofile).permit(:fname, :lname, :bio, :university, :zipcode, :planguage, :slanguage, :smoker, :allergies, :all_desc, :startduration, :endduration, :phone, :image).merge(student: current_student)
	end 

end

app/helpers/studentprofiles_helper.rb
module StudentprofilesHelper
end

app/views/studentprofiles/_form.html.erb
<div class="row" id="profile-form-container">
  <div class="col-md-6 col-md-offset-3 profile-form">
  	<p>Tell us about you <i class="fa fa-smile-o"></i></p>
	<%= form_for @studentprofile, url: studentprofile_path, html: { multipart: true } do |f| %>
	
	<%= f.text_field :fname, placeholder: "First Name" %>

	<%= f.text_field :lname, placeholder: "Last Name" %></br>

	<%= f.text_field :university, placeholder: "University / College"%></br>

	<%= f.text_field :bio, placeholder: "Brief description about yourself" %> </br>
	
	<%= f.text_field :phone, placeholder: "Phone" %> </br>

	<%= f.text_field :planguage, placeholder: "Primary Language" %></br>

	<%= f.text_field :slanguage, placeholder: "Secondary Language" %></br>

	<%= f.text_field :smoker, placeholder: "Smoker / Non-smoker" %></br>

	<%= f.text_field :allergies, placeholder: "Known Allergies" %></br>

	<%= f.text_field :all_desc, placeholder: "Allergy Description" %></br>
	<div class=" profile-select-box">
	<label class="date-label">From</label>
	<%= f.date_field :startduration, placeholder: "from" %> </br>
	</div>
	<div class="profile-select-box">
	<label class="date-label">To</label>
	<%= f.date_field :endduration, placeholder: "to" %>
	</div></br>
	<div class=" profile-select-box">
	<%= f.file_field :image, placeholder: "Select your image", class:'filestyle' %>
	</div></br>

	<%= f.submit :submit, :class=> 'profile-submit-btn'%>

	<% end %>
  </div>
</div>

app/views/studentprofiles/index.html.erb
<% if current_student %>
	Please update your  
	<%= link_to " profile", studentprofile_path %>
<% else %>
	<% nil %>
<% end %>


<% if current_family %>
please update your 
 <%= link_to "profile", familyprofile_path %>
<% else %>
	<% nil %>
<% end %>

<% @studentprofiles.each  do |studentprofile| %>
<h1> Name: <%= studentprofile.fname %>  <%= studentprofile.lname %></h1>
<p> University: <%= studentprofile.university %></p>
<p> About Me: <%= studentprofile.bio %></p>
<% end %>

app/views/studentprofiles/new.html.erb
<%= render 'studentprofiles/form' %>

app/views/studentprofiles/show.html.erb
<div class="profile-container">
  <div class="row">
  	<div class="col-xs-10 col-xs-offset-1 col-s-8 col-s-offset-2 col-md-4 col-md-offset-4 col-lg-6 col-lg-offset-3 profile-image">
	  	<%= image_tag @studentprofile.image.url(:thumb), :class => 'profile-image' %>
	    <p class="profile-name"><span><%= @studentprofile.fname %><%= @studentprofile.lname %></span></p>
	</div><!--.profile-image-->
  </div><!--.row-->

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-s-8 col-s-offset-2 col-md-4 col-md-offset-4 col-lg-6 col-lg-offset-3 profile-info">
	  <p><i class="fa fa-smile-o"></i><span>About:</span><%= @studentprofile.bio%></p>
	  <!-- <p> Phone: <%= @studentprofile.phone %> </p> -->
	  <p><i class="fa fa-graduation-cap"></i><span>University:</span><%= @studentprofile.university %></span></p>
	  <!-- <p> Zipcode: <%= @studentprofile.zipcode %></span></p> -->
    </div><!--.profile-info-->
  </div><!--.row-->

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-s-8 col-s-offset-2 col-md-4 col-md-offset-4 col-lg-6 col-lg-offset-3 profile-info">
	  <p><i class="fa fa-language"></i><span>Primary language:</span><%= @studentprofile.planguage %></p>
	  <p><i class="fa fa-language"></i><span>Other language:</span><%= @studentprofile.slanguage %> </p>
    </div><!--.profile-info-->
  </div><!--.row-->

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-s-8 col-s-offset-2 col-md-4 col-md-offset-4 col-lg-6 col-lg-offset-3 profile-info">
	  <p><i class="fa fa-fire"></i><span>Smoker:</span><%= @studentprofile.smoker %></p>
	  <p><i class="fa fa-medkit"></i><span>Allergies:</span><%= @studentprofile.allergies%></p>
	  <p><i class="fa fa-medkit"></i><span>Type of allergies:</span><%= @studentprofile.all_desc %></p>
	  <p><i class="fa fa-calendar"></i><span>Planing to stay</span></P> 
	  <p><span>From:</span><%= @studentprofile.startduration %><span>To:</span><%= @studentprofile.endduration %> </p>
    </div><!--profile-buttons -->
  </div><!--.row -->

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-s-8 col-s-offset-2 col-md-4 col-md-offset-4 col-lg-6 col-lg-offset-3 profile-buttons">
      <div class="delete-btn">
	    <%= link_to 'Delete', delete_path(@familyprofile), method: :delete, data:{ deletable: true} %>
      </div>
      <div class="edit-btn">
  	    <%= link_to 'Edit', edit_path(@familyprofile) %>
      </div>       
    </div><!--profile-buttons -->
  </div><!--.row -->
</div><!--#profile-container-->
<%= link_to 'Edit', edit_path(@studentprofile) %>
<%= link_to 'Delete', delete_path(@studentprofile), method: :delete, data:{ deletable: true}, class: "delete-btttn" %>


<%= render 'reviews/form' %>