config/routes.rb
Rails.application.routes.draw do


  get '/stuindex', to: 'studentprofiles#index'

 
  get 'reviews/index'

  get 'reviews/new'

  get 'reviews/edit'

  get 'reviews/show'

  get '/studentprofile', to: 'studentprofiles#new'
  post '/studentprofile', to: 'studentprofiles#create'
  get '/studentprofilepage/:id', to: 'studentprofiles#show', as: 'studentprofilepage'
  get '/studentprofilepage/:id/edit', to: 'studentprofiles#edit', as: 'edit'
  delete '/studentprofilepage/:id', to: 'studentprofiles#destroy', as: 'delete', method: :delete

  get '/famindex', to: 'familyprofiles#index'
  get '/familyprofile', to: 'familyprofiles#new'
  post '/familyprofile', to: 'familyprofiles#create'
  get '/familyprofilepage/:id', to: 'familyprofiles#show', as: 'familyprofilepage'
  get '/familyprofilepage/:id/edit', to: 'familyprofiles#edit', as: 'editfamily'
  delete '/familyprofilepage/:id', to: 'familyprofiles#destroy', as: 'deletefamily', method: :delete

  # get '/home', to: 'home#index'
  get '/about', to: 'home#about'

  devise_for :students

  devise_for :families, :controllers => { :omniauth_callbacks => "familyprofile/omniauth_callbacks" }
  devise_scope :family do
  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_families_session
end

  root 'home#index'
  
  

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Intlguest</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	  <script src="https://unpkg.com/masonry-layout@4.0/dist/masonry.pkgd.min.js"></script>
	</head>
	<body>
	  <header>
	  	<nav>
	  		<!-- <p id="nav-logo"> -->
	  			<%= link_to image_tag("/assets/icon.png"), root_path, :class =>"nav-logo" %>
	  		<!-- </p> -->
		  	<ul>
		      <% if flash[:notice] %>
		        <li class="notice"><%= notice %></li>
		      <% end %>
		      <% if flash[:alert] %>
		        <li class="alert"><%= alert %></li>
		      <% end %>
		      
		      <li class="nav-button change-border"><%= link_to 'About', about_path, :class => "change-border__inner" %></li>

			    <% if student_signed_in? %>
			      <li class="nav-button change-border"><%= link_to 'Student Log out', destroy_student_session_path,  method: :delete, :class => "change-border__inner" %></li>
			     <% else %>
			      <li class="nav-button change-border"><%= link_to 'Student Sign up', new_student_registration_path, :class => "change-border__inner" %></li>
			      <li class="nav-button change-border"><%= link_to 'Student Login', student_session_path, :class => "change-border__inner" %></li>
		     	<% end %>

		     	<% if family_signed_in? %>
			      <li class="nav-button change-border"><%= link_to 'Family Log out', destroy_family_session_path,  method: :delete, :class => "change-border__inner" %></li>
			     <% else %>
			      <li class="nav-button change-border"><%= link_to 'Family Sign up', new_family_registration_path, :class => "change-border__inner" %></li>
			      <li class="nav-button change-border"class="button change-border"><%= link_to 'Family Login', family_session_path, :class => "change-border__inner" %></li>
		     	
		     	<% end %>
		     	
			   	<li class="search-box"><%= form_tag(famindex_path, :method => "get",  id: "search-form") do %>
                        <%= text_field_tag :search, params[:search], placeholder: "family by city" %>
                    <% end %> </li>

		    </ul>
		   
	   	</nav>

  	</header>
  


	<%= yield %>

	</body>
</html>